### ISSUE TITLE
Stop deleting comments and mark this as an unofficial port.

### ISSUE THREAD

**Issue by leyxcx** [devs-immortal/The-Aether#220]
All I'm seeing is y'all deleting comments instead of actually marking the mod appropriately. As well as taking the /aether link?? What's wrong with y'all.?.?.?

**Comment by kalucky0** [comment]
If somebody is asking the same question over and over again we remove it to avoid spam. We said multiple times we won't make Forge version.

**Comment by Dragonoidzero** [comment]
That was a single question, they are objecting to us deleting comments *about* this being an unofficial port, as well as asking we mark it as such. I can't speak about the first for I do not moderate the CF page... or really look at it more than once a century, however the reason we are not marked as an unofficial port is because *we aren't a port in the first place*, we are a reimaigining, but you kind of need to get the bases down before you can start majorly innovating.
