### ISSUE TITLE
Weird crash - game is launching without trinkets but it shouldn't.

### ISSUE THREAD

**Issue by K0-RR** [devs-immortal/The-Aether#352]
It should stop and say that trinkets is required because it's mentioned in the fabric.mod.json but for some reason this gets ignored.
https://paste.ee/p/JniAB

**Comment by Jack-Papel** [comment]
Version 1.5.0 doesn't need trinkets, and is incompatible with trinkets. This will be fixed in the next version. Trinkets didn't put out a 1.17.1 version in time for our 1.5.0 update, so we had to use a custom fork of trinkets. If a 1.17.1 version of trinkets is released by our next update, it'll be sure to be used instead.

**Comment by Jack-Papel** [comment]
If you have no other mods that require trinkets, you can remove it entirely, and the aether should work just fine.

**Comment by K0-RR** [comment]
> If you have no other mods that require trinkets, you can remove it entirely, and the aether should work just fine.

The point is - it crashes when I don't add Trinkets.

**Comment by CDAGaming** [comment]
Closing as Invalid, as in 1.5.0+, Trinkets is Jar-In-Jar'd with the Aether. The crash itself was also resolved in Trinkets 3.0.1+ (Which is now packaged with new Aether Builds)
