### ISSUE TITLE
When spinning with boat on quicksoil it crashes

### ISSUE THREAD

**Issue by StevePlayzz** [devs-immortal/The-Aether#48]
I have no crash report but we did talk about it on the discord server, just wanted to put it here so you can keep track of it better. But I still want the feature in-game.

**Comment by Dragonoidzero** [comment]
The crash is a feature too, it is there to make sure you don't have too much fun at once :tater:

**Comment by diabolical17** [comment]
This can easily be fixed by limiting the speed to just below the float max value 😅 

Going over  340,282,346,638,528,860,000,000,000,000,000,000,000.000000 in speed will crash your game haha.

We will limit to  339,282,346,638,528,860,000,000,000,000,000,000,000.000000 somehow 👍🏽

**Comment by Dragonoidzero** [comment]
It may be a good idea to put the limit far lower than that, rn it is impossible to see the boat spinning from the outside, with a lower value it could be visible.

**Comment by diabolical17** [comment]
How about  2,147,483,647? (Int max value)

**Comment by diabolical17** [comment]
Still fast, but not stupid fast.

Boat on ice is 569,000,000ish

**Comment by StevePlayzz** [comment]
That seems reasonable

**Comment by diabolical17** [comment]
Also i really need to try this out lmfao

**Comment by StevePlayzz** [comment]
Yeah lol :D

**Comment by Jack-Papel** [comment]
Latest release [Beta 1.0.1](https://github.com/devs-immortal/The-Aether/releases/tag/b1.0.1):

When spinning quickly in a boat, the F5 front and back cameras are misplaced.
Instead of crashing, it displayed "Invalid move vehicle packet received" as a server disconnect message (I was on a singleplayer world), and booted me to the multiplayer server list.
It seems like the speed cap has been implemented (via this disconnect from the world), but perhaps it needs to be lower than it currently is. 
Exiting a boat when it rotates at such a high speed crashes the game.
Unlike other things on quicksoil, the boat doesn't just keep its speed, it grows its speed (exponentially?) even when not pressing any keys. Might need more than just a speed cap.

See attached:

https://user-images.githubusercontent.com/64770632/112709801-9b24cf80-8e79-11eb-8714-6d39b62eecf6.mp4
![2021-03-26_21 29 37](https://user-images.githubusercontent.com/64770632/112709914-73823700-8e7a-11eb-9c18-120ace3eb82c.png)
