### ISSUE TITLE
Crash: When trying to see anything with REI, the game just crashes

### ISSUE THREAD

**Issue by MontMontgomery** [devs-immortal/The-Aether#608]
### What were you doing when the crash occured? How can we replicate it?

1. First, Have REI (all updated) with Paradise Lost mod
2. Next, Try to see a recipe or just pass the mouse icon over the REI interface (REI items on right side)
3. Finally, The game crashes

[](https://pastebin.com/qDXGdSgM)

### Did it crash the client or server?

Both

### Mod Version

1.6.5 - 1.17

### Fabric API Version

0.12.12

### Crash Report

```shell
https://pastebin.com/tMamPUx5
```

### Other mods

You can see the mods i use in the 'latest.log' in Crash Report.

### Additional Information

Using LauncherPhenix to play

(Couldnt paste the files due to "body is too long (maximum is 65536 characters).")

**Comment by MontMontgomery** [comment]
Idk why, but i linked crash report but it disappeared when i submitted,
anyway [](https://pastebin.com/qDXGdSgM)

**Comment by MontMontgomery** [comment]
https://pastebin.com/qDXGdSgM

**Comment by CDAGaming** [comment]
I remember seeing this type of crash before and its due to whoever has the namespace of "uk.me.desert_island.rer.rei_stuff".

The Aether was not present within the actual trace of this crash, so im obliged to say its due to that other namespace, but @Jack-Papel can feel free to correct me if Im wrong here.

**Comment by MontMontgomery** [comment]
I don't know what that means exactly, can you explain more?

But i tested with various mods, and when i put the Paradise Lost in the game, it just crashes, so i'm pretty sure the Aether mod is the cause for the crash.
Thank you for the help btw!

**Comment by Jack-Papel** [comment]
@CDAGaming I wouldn't be too surprised if it was RecipeConfidence

**Comment by MontMontgomery** [comment]
@Jack-Papel that's weird
i do see the gud_recipe_confidence.jar in my latest.log
i do see Recipe Confidence in Mod Menu 
but i can't see the actual .jar file in my .minecraft mods, i'm dumb or somethin? i'll link prints of my mods (some aren't in the actual name for some reasons, don't mind)
![image](https://user-images.githubusercontent.com/93541980/154861723-84bfb6fb-cc84-4416-bf1b-2146a4c474f1.png)

(Towelette is disabled via LauncherFenix tool)

**Comment by Jack-Papel** [comment]
Nope, you're not dumb. RecipeConfidence is a library we use for certain recipe stuff. It's included in the jar file of our mod, so you won't see it in your folder

**Comment by MontMontgomery** [comment]
Okay, thanks

**Comment by Jack-Papel** [comment]
From the logs, it looks to me like an issue with a Modern Industrialization REI plugin, but I'm not entirely sure. Though I don't think it's Paradise Lost causing it.
I recommend forwarding the issue to RoughlyEnoughItems, since they can probably diagnose the issue better than we can, or to Modern Industrialization.

**Comment by MontMontgomery** [comment]
Okay, i'll do that, but so the issue is compability with Modern Industrialization? 
Because i am currently in my world with 150+ hours, and decided to put some adventure mod (and i cant even use REI in my world now, and can't load my world without Paradise Lost), and never crashed like that

**Comment by MBatt1** [comment]
Has this been resolved @MontMontgomery @Jack-Papel ?

**Comment by MontMontgomery** [comment]
> Has this been resolved @MontMontgomery @Jack-Papel ?

Nope

**Comment by Jack-Papel** [comment]
> and decided to put some adventure mod 

Oh, I missed this before. The crash only occurs with this adventure mod? What's the mod called?

**Comment by MontMontgomery** [comment]
> > and decided to put some adventure mod 
> 
> Oh, I missed this before. The crash only occurs with this adventure mod? What's the mod called?

Just Paradise Lost crashes, if a disable Paradise Lost, the game works just fine with REI

**Comment by MBatt1** [comment]
Looks like the actual error is caused by RoughlyEnoughResources, which must have some strange interaction with one of our dependencies, recipe confidence. Unfortunately it looks like you're playing on 1.17 which we can't easily support any longer, but removing RoughlyEnoughResources likely will fix the problem
